name: Trigger Playwright Tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Playwright Repository
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PLAYWRIGHT_PAT }}" \
            https://api.github.com/repos/j3-m2stack/playwright_test/dispatches \
            -d '{
              "event_type": "run-playwright",
              "client_payload": {
                "pr_number": "${{ github.event.pull_request.number }}"
              }
            }'
  